# Generated by Django 3.2.4 on 2021-06-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200, null=True)),
                ('cpu', models.CharField(max_length=200)),
                ('cpu_cores', models.CharField(max_length=200)),
                ('cpu_clock_mhz', models.CharField(max_length=200)),
                ('flash_mb', models.CharField(max_length=200)),
                ('ram_mb', models.CharField(max_length=200)),
                ('ethernet_100MB_ports', models.CharField(max_length=200)),
                ('ethernet_gbit_ports', models.CharField(max_length=200)),
                ('wlan_24ghz', models.CharField(max_length=200)),
                ('wlan_50ghz', models.CharField(max_length=200)),
                ('bluetooth_support', models.CharField(max_length=200)),
                ('usb_ports', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200, null=True)),
                ('power_supply', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registery_date', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.equipmentmodel')),
            ],
        ),
    ]
